namespace: gh-arc-runners
runners:
  ccppjhub:
    name: ccpp-jhub-runner
  micm:
    name: micm-runner
  nbviz:
    name: nbviz-runner
  nickknows:
    name: nickknows-runner
  samurai:
    name: samurai-runner
  skitunes:
    name: skitunes-runner
