runners:
  nickknows:
    name: nickknows-runner
  skitunes:
    name: skitunes-runner
  samurai:
    name: samurai-runner
  micm:
    name: micm-runner
  ccpp-jhub:
    name: ccpp-jhub-runner
namespace: gh-arc-runners
githubConfigSecret:
  github_token:
    valueFrom:
      secretKeyRef:
        name: ncote-github-token
        key: token