apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ .Release.Name }}-{{ .Values.jhubs.nbviz.name }}'
  namespace: argo
spec:
  destination:
    namespace: '''{{ .Values.namespace }}'''
    server: https://kubernetes.default.svc
  project: default
  sources:
  - helm:
      valueFiles:
      - $values/gha-runner-scale-set/nbviz-values.yaml
    path: gha-runner-scale-set
    repoURL: https://github.com/Gin-G/argo-k8s-stuff
    targetRevision: main
  - ref: values
    repoURL: https://github.com/NicholasCote/cirrus-GitHub-Runners
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
