apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ .Release.Name }}-{{ .Values.runners.nickknows.name }}'
  namespace: argo
spec:
  project: default
  sources:
    - repoURL: https://github.com/Gin-G/argo-k8s-stuff
      path: gha-runner-scale-set
      targetRevision: main
      helm:
        valueFiles: 
          - $values/GHRunner-scale-set/nickknows-values.yaml
    - repoURL: 'https://github.com/NicholasCote/cirrus-GitHub-Runners'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: '{{ .Values.namespace }}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
            